site_name: dataframe-io
repo_url: https://github.com/chr1st1ank/dframeio
repo_name: dframeio
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API documentation: mkapi/api/dframeio
  - Contributing: contributing.md
theme:
  name: readthedocs
  language: en
  highlightjs: true
markdown_extensions:
  - admonition
  - toc:
      baselevel: 1
      permalink: true
  - meta
plugins:
  - include-markdown
  - autorefs
  - search:
      lang: en
  - mkapi:
      src_dirs:
        - dframeio
